### ISSUE TITLE
I was minding my own business when suddenly...

### ISSUE THREAD

**Issue by thewhiterabbit** [enyo/dropzone-test2#1]
Han shot first!

But seriously, I was wondering if there's a way to debug the ajax responses without hacking into the js file because I'm not getting any errors in my php log, but the files aren't uploading.

Usually I output ajax responses to the console for debug, but I was hoping you, being the genius that you are, had put in secret debug mode.

Cool song btw.

**Comment by enyo** [comment]
Ha :)
I normally just use the browser network inspector to debug uploads like this. There aren't specific debugging tools in dropzone.

Hope you'll find your issue!
